name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-bicep:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    
    - name: login to azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        

    # - name: Deploy Bicep template
    #   uses: azure/arm-deploy@v0
    #   with:
    #     scope: resourcegroup
    #     resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}  # Define in GitHub secrets
    #     template: ./bicep/environments/vnet.bicep               # Path to your Bicep file
    #     parameters: |
    #       vnetName=sandbox-dev
    #       location=East US
    #     deploymentName: vnet-deployment